"""update supplier packing lists and items to match payload

Revision ID: 0fd445b52e66
Revises: 77905153bed0
Create Date: 2026-09-08 10:19:35.494170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fd445b52e66'
down_revision = '77905153bed0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplier_packing_list_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('material_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(length=500), nullable=False))
        batch_op.add_column(sa.Column('hsn_code', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('unit_price', sa.Numeric(precision=18, scale=2), nullable=False))
        batch_op.add_column(sa.Column('net_amount', sa.Numeric(precision=18, scale=2), nullable=True))
        batch_op.add_column(sa.Column('weight', sa.Numeric(precision=18, scale=3), nullable=True))
        batch_op.add_column(sa.Column('unit_weight', sa.Numeric(precision=18, scale=3), nullable=True))
        batch_op.add_column(sa.Column('total_weight', sa.Numeric(precision=18, scale=3), nullable=True))
        batch_op.drop_column('unit_weight_kg')
        batch_op.drop_column('material_description')

    with op.batch_alter_table('supplier_packing_lists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('packing_list_no', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('weight', sa.Numeric(precision=18, scale=3), nullable=True))
        batch_op.add_column(sa.Column('total_weight', sa.Numeric(precision=18, scale=3), nullable=True))
        batch_op.drop_index(batch_op.f('ix_supplier_packing_lists_project_id'))
        batch_op.create_index(batch_op.f('ix_supplier_packing_lists_project_id'), ['project_id'], unique=True)
        batch_op.drop_column('packing_list_number')
        batch_op.drop_column('total_gross_weight_kg')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplier_packing_lists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_gross_weight_kg', sa.NUMERIC(precision=18, scale=3), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('packing_list_number', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_index(batch_op.f('ix_supplier_packing_lists_project_id'))
        batch_op.create_index(batch_op.f('ix_supplier_packing_lists_project_id'), ['project_id'], unique=False)
        batch_op.drop_column('total_weight')
        batch_op.drop_column('weight')
        batch_op.drop_column('packing_list_no')

    with op.batch_alter_table('supplier_packing_list_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('material_description', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('unit_weight_kg', sa.NUMERIC(precision=18, scale=3), autoincrement=False, nullable=False))
        batch_op.drop_column('total_weight')
        batch_op.drop_column('unit_weight')
        batch_op.drop_column('weight')
        batch_op.drop_column('net_amount')
        batch_op.drop_column('unit_price')
        batch_op.drop_column('hsn_code')
        batch_op.drop_column('description')
        batch_op.drop_column('material_name')

    # ### end Alembic commands ###

