"""add fields to customer quotations and items

Revision ID: 11ec26e3fbb3
Revises: f132403f7f44
Create Date: 2026-09-04 10:55:27.493353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11ec26e3fbb3'
down_revision = 'f132403f7f44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_quotation_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost_sheet_item_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('quotation_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('item_code', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('net_amount', sa.Numeric(precision=18, scale=2), nullable=True))
        batch_op.add_column(sa.Column('customs_duty_rate', sa.Numeric(precision=5, scale=4), nullable=True))
        batch_op.alter_column('unit_price',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=True)
        batch_op.create_foreign_key(None, 'cost_sheet_items', ['cost_sheet_item_id'], ['id'])

    with op.batch_alter_table('customer_quotations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quotation_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('currency_unit', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('currency_symbol', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('total_net_amount', sa.Numeric(precision=18, scale=2), nullable=True))
        batch_op.add_column(sa.Column('validity', sa.String(length=100), nullable=True))
        batch_op.alter_column('qo_number',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_quotations', schema=None) as batch_op:
        batch_op.alter_column('qo_number',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('validity')
        batch_op.drop_column('total_net_amount')
        batch_op.drop_column('currency_symbol')
        batch_op.drop_column('currency_unit')
        batch_op.drop_column('quotation_number')

    with op.batch_alter_table('customer_quotation_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('unit_price',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=False)
        batch_op.drop_column('customs_duty_rate')
        batch_op.drop_column('net_amount')
        batch_op.drop_column('item_code')
        batch_op.drop_column('quotation_number')
        batch_op.drop_column('cost_sheet_item_id')

    # ### end Alembic commands ###
