"""add warranty_period to supplier_quotations

Revision ID: 14b8a28430ea
Revises: e2f891a27b14
Create Date: 2026-09-25 14:37:36.098904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14b8a28430ea'
down_revision = 'e2f891a27b14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplier_quotations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('warranty_period', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplier_quotations', schema=None) as batch_op:
        batch_op.drop_column('warranty_period')

    # ### end Alembic commands ###
