"""add workflow models group 3

Revision ID: 17f9c47425ed
Revises: c383809b6282
Create Date: 2026-08-25 18:12:51.574245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17f9c47425ed'
down_revision = 'c383809b6282'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_tenders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('company_business_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('website', sa.String(length=2048), nullable=True),
    sa.Column('contact_number', sa.String(length=30), nullable=False),
    sa.Column('tender_title', sa.String(length=255), nullable=False),
    sa.Column('tender_number', sa.String(length=100), nullable=False),
    sa.Column('tender_date', sa.Date(), nullable=False),
    sa.Column('tender_opening_date', sa.Date(), nullable=False),
    sa.Column('opening_time', sa.Time(), nullable=False),
    sa.Column('closing_date', sa.Date(), nullable=False),
    sa.Column('closing_time', sa.Time(), nullable=False),
    sa.Column('gst_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('tender_fee', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('validity', sa.String(length=100), nullable=True),
    sa.Column('incoterms', sa.String(length=50), nullable=True),
    sa.Column('delivery_period', sa.String(length=100), nullable=True),
    sa.Column('payment_terms', sa.String(length=255), nullable=True),
    sa.Column('warranty_period', sa.String(length=100), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customer_tenders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_tenders_project_id'), ['project_id'], unique=False)

    op.create_table('bid_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('tender_id', sa.Integer(), nullable=False),
    sa.Column('tender_name', sa.String(length=255), nullable=False),
    sa.Column('submission_date', sa.Date(), nullable=False),
    sa.Column('submission_number', sa.String(length=100), nullable=False),
    sa.Column('delivery_term', sa.String(length=100), nullable=True),
    sa.Column('period', sa.String(length=100), nullable=True),
    sa.Column('payment_term', sa.String(length=255), nullable=True),
    sa.Column('validity', sa.String(length=100), nullable=True),
    sa.Column('warranty_period', sa.String(length=100), nullable=True),
    sa.Column('gst_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['tender_id'], ['customer_tenders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bid_submissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bid_submissions_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bid_submissions_tender_id'), ['tender_id'], unique=False)

    op.create_table('customer_tender_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_tender_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('hsn_sac', sa.String(length=50), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_tender_id'], ['customer_tenders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customer_tender_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_tender_items_customer_tender_id'), ['customer_tender_id'], unique=False)

    op.create_table('purchase_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('tender_id', sa.Integer(), nullable=True),
    sa.Column('po_title', sa.String(length=255), nullable=False),
    sa.Column('po_number', sa.String(length=100), nullable=False),
    sa.Column('poc_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('contact', sa.String(length=30), nullable=True),
    sa.Column('po_date', sa.Date(), nullable=False),
    sa.Column('gst', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('delivery_date', sa.Date(), nullable=True),
    sa.Column('delivery_term', sa.String(length=100), nullable=True),
    sa.Column('payment_terms', sa.String(length=255), nullable=True),
    sa.Column('warranty_period', sa.String(length=100), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['tender_id'], ['customer_tenders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_orders_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_orders_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_orders_tender_id'), ['tender_id'], unique=False)

    op.create_table('bid_submission_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bid_submission_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('hsn_sac', sa.String(length=50), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bid_submission_id'], ['bid_submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bid_submission_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bid_submission_items_bid_submission_id'), ['bid_submission_id'], unique=False)

    op.create_table('purchase_order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_order_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('hsn_code', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase_order_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_order_items_purchase_order_id'), ['purchase_order_id'], unique=False)

    op.create_table('supplier_order_confirmations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('purchase_order_id', sa.Integer(), nullable=True),
    sa.Column('confirmation_date', sa.Date(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('reference_number', sa.String(length=100), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('shipping_term', sa.String(length=100), nullable=True),
    sa.Column('delivery_term', sa.String(length=100), nullable=True),
    sa.Column('payment_terms', sa.String(length=255), nullable=True),
    sa.Column('warranty_period', sa.String(length=100), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('supplier_order_confirmations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supplier_order_confirmations_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_order_confirmations_purchase_order_id'), ['purchase_order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_order_confirmations_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('supplier_order_confirmation_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_order_confirmation_id', sa.Integer(), nullable=False),
    sa.Column('item_description', sa.String(length=500), nullable=False),
    sa.Column('hsn', sa.String(length=50), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['supplier_order_confirmation_id'], ['supplier_order_confirmations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('supplier_order_confirmation_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supplier_order_confirmation_items_supplier_order_confirmation_id'), ['supplier_order_confirmation_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplier_order_confirmation_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supplier_order_confirmation_items_supplier_order_confirmation_id'))

    op.drop_table('supplier_order_confirmation_items')
    with op.batch_alter_table('supplier_order_confirmations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supplier_order_confirmations_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_supplier_order_confirmations_purchase_order_id'))
        batch_op.drop_index(batch_op.f('ix_supplier_order_confirmations_project_id'))

    op.drop_table('supplier_order_confirmations')
    with op.batch_alter_table('purchase_order_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_order_items_purchase_order_id'))

    op.drop_table('purchase_order_items')
    with op.batch_alter_table('bid_submission_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bid_submission_items_bid_submission_id'))

    op.drop_table('bid_submission_items')
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_orders_tender_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_orders_project_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_orders_customer_id'))

    op.drop_table('purchase_orders')
    with op.batch_alter_table('customer_tender_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_tender_items_customer_tender_id'))

    op.drop_table('customer_tender_items')
    with op.batch_alter_table('bid_submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bid_submissions_tender_id'))
        batch_op.drop_index(batch_op.f('ix_bid_submissions_project_id'))

    op.drop_table('bid_submissions')
    with op.batch_alter_table('customer_tenders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_tenders_project_id'))

    op.drop_table('customer_tenders')
    # ### end Alembic commands ###
