"""update bid_submissions and bid_submission_items schema

Revision ID: 361f23c961e8
Revises: a0c9fa21b27d
Create Date: 2026-09-04 15:13:43.640099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '361f23c961e8'
down_revision = 'a0c9fa21b27d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bid_submission_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('net_total', sa.Numeric(precision=18, scale=2), nullable=True))
        batch_op.add_column(sa.Column('total', sa.Numeric(precision=18, scale=2), nullable=True))

    with op.batch_alter_table('bid_submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tender_title', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('tender_number', sa.String(length=100), nullable=False))
        batch_op.alter_column('tender_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('submission_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               nullable=True)
        batch_op.drop_column('tender_name')
        batch_op.drop_column('submission_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bid_submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('submission_number', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('tender_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.alter_column('submission_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               nullable=False)
        batch_op.alter_column('tender_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('tender_number')
        batch_op.drop_column('tender_title')

    with op.batch_alter_table('bid_submission_items', schema=None) as batch_op:
        batch_op.drop_column('total')
        batch_op.drop_column('net_total')

    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attachments_entity'), ['entity_type', 'entity_id'], unique=False)

    # ### end Alembic commands ###
