"""add quotation request step 2 fields

Revision ID: 366c1a4ee897
Revises: a6a333f08fd2
Create Date: 2026-09-01 14:56:03.573510

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '366c1a4ee897'
down_revision = 'a6a333f08fd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_steps', schema=None) as batch_op:
        batch_op.alter_column('data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('uq_project_steps_project_step'), type_='unique')
        batch_op.create_unique_constraint('uq_project_step_number', ['project_id', 'step_number'])
        batch_op.drop_constraint(batch_op.f('ck_project_steps_status'), type_='check')
        batch_op.drop_constraint(batch_op.f('ck_project_steps_step_number'), type_='check')
        batch_op.create_check_constraint('ck_project_step_number', 'step_number BETWEEN 1 AND 15')
        batch_op.create_check_constraint('ck_project_step_status', "status IN ('pending', 'in_progress', 'completed')")

    with op.batch_alter_table('quotation_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quotation_requested_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('supplier_contacted', sa.Boolean(), nullable=False))
        batch_op.create_unique_constraint('uq_quotation_request_project_supplier', ['project_id', 'supplier_id'])
        batch_op.drop_column('request_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotation_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('request_date', sa.DATE(), autoincrement=False, nullable=False))
        batch_op.drop_constraint('uq_quotation_request_project_supplier', type_='unique')
        batch_op.drop_column('supplier_contacted')
        batch_op.drop_column('quotation_requested_date')

    with op.batch_alter_table('project_steps', schema=None) as batch_op:
        batch_op.drop_constraint('ck_project_step_status', type_='check')
        batch_op.drop_constraint('ck_project_step_number', type_='check')
        batch_op.create_check_constraint(batch_op.f('ck_project_steps_step_number'), 'step_number >= 1 AND step_number <= 15')
        batch_op.create_check_constraint(batch_op.f('ck_project_steps_status'), "status::text = ANY (ARRAY['pending'::character varying, 'in_progress'::character varying, 'completed'::character varying]::text[])")
        batch_op.drop_constraint('uq_project_step_number', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_project_steps_project_step'), ['project_id', 'step_number'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)

    # ### end Alembic commands ###
