"""add_customer_and_supplier_address_segregation_and_pocs

Revision ID: 4fd43ceb190c
Revises: 8f1c3d5e7a9b
Create Date: 2026-09-23 13:49:40.812271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fd43ceb190c'
down_revision = '8f1c3d5e7a9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_pocs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('contact_number', sa.String(length=30), nullable=True),
    sa.Column('designation', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customer_pocs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_pocs_customer_id'), ['customer_id'], unique=False)

    op.create_table('supplier_pocs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('contact_number', sa.String(length=30), nullable=True),
    sa.Column('designation', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('supplier_pocs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supplier_pocs_supplier_id'), ['supplier_id'], unique=False)

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nickname', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('street', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('area', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('pincode', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(length=100), nullable=True))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('contact_number',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
        batch_op.alter_column('address',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nickname', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('street', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('area', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('pincode', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(length=100), nullable=True))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('contact_number',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
        batch_op.alter_column('address',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.alter_column('address',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('contact_number',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('country')
        batch_op.drop_column('pincode')
        batch_op.drop_column('state')
        batch_op.drop_column('city')
        batch_op.drop_column('area')
        batch_op.drop_column('street')
        batch_op.drop_column('nickname')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.alter_column('address',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('contact_number',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('country')
        batch_op.drop_column('pincode')
        batch_op.drop_column('state')
        batch_op.drop_column('city')
        batch_op.drop_column('area')
        batch_op.drop_column('street')
        batch_op.drop_column('nickname')


    with op.batch_alter_table('supplier_pocs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supplier_pocs_supplier_id'))

    op.drop_table('supplier_pocs')
    with op.batch_alter_table('customer_pocs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_pocs_customer_id'))

    op.drop_table('customer_pocs')
    # ### end Alembic commands ###
