"""create step_remarks table

Revision ID: 5af1fc57ffff
Revises: c23939b15c31
Create Date: 2026-09-23 16:01:23.700856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5af1fc57ffff'
down_revision = 'c23939b15c31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('step_remarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('remark', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('step_number BETWEEN 1 AND 15', name='ck_step_remarks_step_number'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('step_remarks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_step_remarks_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_step_remarks_step_number'), ['step_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_step_remarks_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('step_remarks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_step_remarks_user_id'))
        batch_op.drop_index(batch_op.f('ix_step_remarks_step_number'))
        batch_op.drop_index(batch_op.f('ix_step_remarks_project_id'))

    op.drop_table('step_remarks')
    # ### end Alembic commands ###
