"""change attachments to project and step

Revision ID: 74681f9a58fb
Revises: 7d2dcfe63084
Create Date: 2026-08-31 15:00:34.487349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74681f9a58fb'
down_revision = '7d2dcfe63084'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('step_number', sa.Integer(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_attachments_entity'))
        batch_op.drop_index(batch_op.f('ix_attachments_entity_id'))
        batch_op.drop_index(batch_op.f('ix_attachments_entity_type'))
        batch_op.create_index(batch_op.f('ix_attachments_project_id'), ['project_id'], unique=False)
        batch_op.create_index('ix_attachments_project_step', ['project_id', 'step_number'], unique=False)
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'])
        batch_op.drop_column('entity_id')
        batch_op.drop_column('entity_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entity_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('entity_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index('ix_attachments_project_step')
        batch_op.drop_index(batch_op.f('ix_attachments_project_id'))
        batch_op.create_index(batch_op.f('ix_attachments_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_attachments_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attachments_entity'), ['entity_type', 'entity_id'], unique=False)
        batch_op.drop_column('step_number')
        batch_op.drop_column('project_id')

    # ### end Alembic commands ###
