"""update supplier invoices and items schema

Revision ID: 77905153bed0
Revises: bc864b5fd97e
Create Date: 2026-09-07 18:09:16.260265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77905153bed0'
down_revision = 'bc864b5fd97e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplier_invoice_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('material_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('hsn_code', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('net_amount', sa.Numeric(precision=18, scale=2), nullable=True))
        batch_op.drop_column('hsn_sac')

    with op.batch_alter_table('supplier_invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoice_no', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('delivery_period', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('total_amount', sa.Numeric(precision=18, scale=2), nullable=True))
        batch_op.add_column(sa.Column('total_net_amount', sa.Numeric(precision=18, scale=2), nullable=True))
        batch_op.drop_index(batch_op.f('ix_supplier_invoices_project_id'))
        batch_op.create_index(batch_op.f('ix_supplier_invoices_project_id'), ['project_id'], unique=True)
        batch_op.drop_column('currency')
        batch_op.drop_column('invoice_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplier_invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoice_number', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('currency', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
        batch_op.drop_index(batch_op.f('ix_supplier_invoices_project_id'))
        batch_op.create_index(batch_op.f('ix_supplier_invoices_project_id'), ['project_id'], unique=False)
        batch_op.drop_column('total_net_amount')
        batch_op.drop_column('total_amount')
        batch_op.drop_column('delivery_period')
        batch_op.drop_column('invoice_no')

    with op.batch_alter_table('supplier_invoice_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hsn_sac', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_column('net_amount')
        batch_op.drop_column('hsn_code')
        batch_op.drop_column('material_name')

    # ### end Alembic commands ###
