"""update supplier order confirmation and items schema

Revision ID: 78ab2fcebc93
Revises: ea3c148f0567
Create Date: 2026-09-07 15:12:56.514111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78ab2fcebc93'
down_revision = 'ea3c148f0567'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplier_order_confirmation_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('material_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(length=500), nullable=False))
        batch_op.add_column(sa.Column('hsn_code', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('net_amount', sa.Numeric(precision=18, scale=2), nullable=True))
        batch_op.drop_column('item_description')
        batch_op.drop_column('hsn')

    with op.batch_alter_table('supplier_order_confirmations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_confirmation_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('ref_no', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('shipping_terms', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('delivery_period', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('total_amount', sa.Numeric(precision=18, scale=2), nullable=True))
        batch_op.add_column(sa.Column('total_net_amount', sa.Numeric(precision=18, scale=2), nullable=True))
        batch_op.drop_index(batch_op.f('ix_supplier_order_confirmations_project_id'))
        batch_op.create_index(batch_op.f('ix_supplier_order_confirmations_project_id'), ['project_id'], unique=True)
        batch_op.drop_column('shipping_term')
        batch_op.drop_column('confirmation_date')
        batch_op.drop_column('currency')
        batch_op.drop_column('reference_number')
        batch_op.drop_column('delivery_term')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplier_order_confirmations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_term', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('reference_number', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('currency', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('confirmation_date', sa.DATE(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('shipping_term', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_supplier_order_confirmations_project_id'))
        batch_op.create_index(batch_op.f('ix_supplier_order_confirmations_project_id'), ['project_id'], unique=False)
        batch_op.drop_column('total_net_amount')
        batch_op.drop_column('total_amount')
        batch_op.drop_column('delivery_period')
        batch_op.drop_column('shipping_terms')
        batch_op.drop_column('ref_no')
        batch_op.drop_column('order_confirmation_date')

    with op.batch_alter_table('supplier_order_confirmation_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hsn', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('item_description', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
        batch_op.drop_column('net_amount')
        batch_op.drop_column('hsn_code')
        batch_op.drop_column('description')
        batch_op.drop_column('material_name')

    # ### end Alembic commands ###
