"""add customer query step

Revision ID: 8becc6307029
Revises: e4d4f7e5fd2f
Create Date: 2026-08-25 17:47:28.533439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8becc6307029'
down_revision = 'e4d4f7e5fd2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_queries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('qo_date', sa.Date(), nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customer_queries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_queries_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_queries_project_id'), ['project_id'], unique=False)

    op.create_table('customer_query_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_query_id', sa.Integer(), nullable=False),
    sa.Column('material_name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_query_id'], ['customer_queries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customer_query_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_query_items_customer_query_id'), ['customer_query_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_query_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_query_items_customer_query_id'))

    op.drop_table('customer_query_items')
    with op.batch_alter_table('customer_queries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_queries_project_id'))
        batch_op.drop_index(batch_op.f('ix_customer_queries_customer_id'))

    op.drop_table('customer_queries')
    # ### end Alembic commands ###
