"""update customer_tenders and customer_tender_items schema

Revision ID: a0c9fa21b27d
Revises: 11ec26e3fbb3
Create Date: 2026-09-04 12:25:03.214558

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a0c9fa21b27d'
down_revision = '11ec26e3fbb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('customer_tender_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_code', sa.String(length=100), nullable=True))
        batch_op.drop_column('hsn_sac')
        batch_op.drop_column('unit_price')

    with op.batch_alter_table('customer_tenders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('officer_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('opening_date_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('closing_date_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('delivery_terms', sa.String(length=255), nullable=True))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('address',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('contact_number',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
        batch_op.alter_column('tender_title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('tender_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_customer_tenders_customer_id'), ['customer_id'], unique=False)
        batch_op.create_foreign_key(None, 'customers', ['customer_id'], ['id'])
        batch_op.drop_column('incoterms')
        batch_op.drop_column('gst_rate')
        batch_op.drop_column('tender_opening_date')
        batch_op.drop_column('closing_time')
        batch_op.drop_column('opening_time')
        batch_op.drop_column('closing_date')
        batch_op.drop_column('company_business_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_tenders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_business_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('closing_date', sa.DATE(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('opening_time', postgresql.TIME(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('closing_time', postgresql.TIME(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('tender_opening_date', sa.DATE(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('gst_rate', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('incoterms', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_customer_tenders_customer_id'))
        batch_op.alter_column('tender_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               nullable=False)
        batch_op.alter_column('tender_title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('contact_number',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
        batch_op.alter_column('address',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('delivery_terms')
        batch_op.drop_column('closing_date_time')
        batch_op.drop_column('opening_date_time')
        batch_op.drop_column('officer_name')
        batch_op.drop_column('customer_id')

    with op.batch_alter_table('customer_tender_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_price', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('hsn_sac', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_column('item_code')

    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attachments_entity'), ['entity_type', 'entity_id'], unique=False)

    # ### end Alembic commands ###
