"""create materials table

Revision ID: a6a333f08fd2
Revises: 094a24694878
Create Date: 2026-08-31 20:10:41.772344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6a333f08fd2'
down_revision = '094a24694878'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_code', sa.String(length=100), nullable=False),
    sa.Column('material_name', sa.String(length=255), nullable=False),
    sa.Column('hsn_code', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_materials_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_materials_material_code'), ['material_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_materials_material_name'), ['material_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_materials_material_name'))
        batch_op.drop_index(batch_op.f('ix_materials_material_code'))
        batch_op.drop_index(batch_op.f('ix_materials_is_active'))

    op.drop_table('materials')
    # ### end Alembic commands ###
