"""add customer and supplier payment models

Revision ID: a84f419b400a
Revises: f6e2556b2a52
Create Date: 2026-08-26 10:12:13.092674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a84f419b400a'
down_revision = 'f6e2556b2a52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_delivery_invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=100), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('gst_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('round_off', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customer_delivery_invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_delivery_invoices_project_id'), ['project_id'], unique=False)

    op.create_table('customer_delivery_packing_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('packing_list_number', sa.String(length=100), nullable=False),
    sa.Column('packing_list_date', sa.Date(), nullable=False),
    sa.Column('total_no_of_packs', sa.Integer(), nullable=True),
    sa.Column('packing_condition', sa.String(length=255), nullable=True),
    sa.Column('net_weight_kg', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.Column('gross_weight_kg', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customer_delivery_packing_lists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_delivery_packing_lists_project_id'), ['project_id'], unique=False)

    op.create_table('customer_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=100), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('invoice_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('payment_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('liquidated_damages', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('tds', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customer_payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_payments_project_id'), ['project_id'], unique=False)

    op.create_table('delivery_challans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('delivery_challan_number', sa.String(length=100), nullable=False),
    sa.Column('delivery_challan_date', sa.Date(), nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('delivery_challans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_delivery_challans_project_id'), ['project_id'], unique=False)

    op.create_table('supplier_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('amount_paid_currency', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('amount_paid_inr', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('transaction_details', sa.Text(), nullable=True),
    sa.Column('pending_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('supplier_payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supplier_payments_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_payments_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('transport_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('transportation_mode', sa.String(length=100), nullable=False),
    sa.Column('lr_number', sa.String(length=100), nullable=True),
    sa.Column('transport_date', sa.Date(), nullable=False),
    sa.Column('from_location', sa.String(length=255), nullable=False),
    sa.Column('to_location', sa.String(length=255), nullable=False),
    sa.Column('transport_charges', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transport_details', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transport_details_project_id'), ['project_id'], unique=False)

    op.create_table('warranty_certificates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('certificate_date', sa.Date(), nullable=False),
    sa.Column('warranty_period', sa.String(length=100), nullable=False),
    sa.Column('po_number', sa.String(length=100), nullable=True),
    sa.Column('po_date', sa.Date(), nullable=True),
    sa.Column('invoice_number', sa.String(length=100), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('warranty_certificates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_warranty_certificates_project_id'), ['project_id'], unique=False)

    op.create_table('customer_delivery_invoice_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('material_description', sa.String(length=500), nullable=False),
    sa.Column('hsn_sac', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('rate_per_unit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['customer_delivery_invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customer_delivery_invoice_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_delivery_invoice_items_invoice_id'), ['invoice_id'], unique=False)

    op.create_table('customer_delivery_packing_list_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('packing_list_id', sa.Integer(), nullable=False),
    sa.Column('material_description', sa.String(length=500), nullable=False),
    sa.Column('hsn_sac', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('weight_per_unit_kg', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('total_weight_kg', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['packing_list_id'], ['customer_delivery_packing_lists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customer_delivery_packing_list_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_delivery_packing_list_items_packing_list_id'), ['packing_list_id'], unique=False)

    op.create_table('delivery_challan_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('delivery_challan_id', sa.Integer(), nullable=False),
    sa.Column('material_description', sa.String(length=500), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('rate_per_unit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['delivery_challan_id'], ['delivery_challans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('delivery_challan_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_delivery_challan_items_delivery_challan_id'), ['delivery_challan_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery_challan_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_delivery_challan_items_delivery_challan_id'))

    op.drop_table('delivery_challan_items')
    with op.batch_alter_table('customer_delivery_packing_list_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_delivery_packing_list_items_packing_list_id'))

    op.drop_table('customer_delivery_packing_list_items')
    with op.batch_alter_table('customer_delivery_invoice_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_delivery_invoice_items_invoice_id'))

    op.drop_table('customer_delivery_invoice_items')
    with op.batch_alter_table('warranty_certificates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_warranty_certificates_project_id'))

    op.drop_table('warranty_certificates')
    with op.batch_alter_table('transport_details', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transport_details_project_id'))

    op.drop_table('transport_details')
    with op.batch_alter_table('supplier_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supplier_payments_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_supplier_payments_project_id'))

    op.drop_table('supplier_payments')
    with op.batch_alter_table('delivery_challans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_delivery_challans_project_id'))

    op.drop_table('delivery_challans')
    with op.batch_alter_table('customer_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_payments_project_id'))

    op.drop_table('customer_payments')
    with op.batch_alter_table('customer_delivery_packing_lists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_delivery_packing_lists_project_id'))

    op.drop_table('customer_delivery_packing_lists')
    with op.batch_alter_table('customer_delivery_invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_delivery_invoices_project_id'))

    op.drop_table('customer_delivery_invoices')
    # ### end Alembic commands ###
