"""create project steps

Revision ID: bfacc4c67adf
Revises: d5d8e228db08
Create Date: 2026-08-27 15:27:42.654404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfacc4c67adf'
down_revision = 'd5d8e228db08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'in_progress', 'completed')", name='ck_project_steps_status'),
    sa.CheckConstraint('step_number BETWEEN 1 AND 15', name='ck_project_steps_step_number'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'step_number', name='uq_project_steps_project_step')
    )
    with op.batch_alter_table('project_steps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_steps_project_id'), ['project_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_steps_project_id'))

    op.drop_table('project_steps')
    # ### end Alembic commands ###
