"""add project_code to projects table

Revision ID: c23939b15c31
Revises: 4fd43ceb190c
Create Date: 2026-09-23 14:14:04.627493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c23939b15c31'
down_revision = '4fd43ceb190c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_code', sa.String(length=100), nullable=True))
        batch_op.create_index(batch_op.f('ix_projects_project_code'), ['project_code'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_project_code'))
        batch_op.drop_column('project_code')

    # ### end Alembic commands ###
