"""add workflow models group 2

Revision ID: c383809b6282
Revises: 8becc6307029
Create Date: 2026-08-25 18:00:33.183677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c383809b6282'
down_revision = '8becc6307029'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_quotations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('qo_number', sa.String(length=100), nullable=False),
    sa.Column('quotation_date', sa.Date(), nullable=False),
    sa.Column('quotation_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customer_quotations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_quotations_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_quotations_project_id'), ['project_id'], unique=False)

    op.create_table('quotation_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('request_date', sa.Date(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quotation_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quotation_requests_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quotation_requests_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('supplier_quotations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('quotation_number', sa.String(length=100), nullable=False),
    sa.Column('quotation_date', sa.Date(), nullable=False),
    sa.Column('quotation_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('validity', sa.String(length=100), nullable=True),
    sa.Column('incoterms', sa.String(length=50), nullable=True),
    sa.Column('payment_terms', sa.String(length=255), nullable=True),
    sa.Column('delivery_period', sa.String(length=100), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('supplier_quotations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supplier_quotations_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_quotations_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('customer_quotation_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_quotation_id', sa.Integer(), nullable=False),
    sa.Column('material_name', sa.String(length=255), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_quotation_id'], ['customer_quotations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customer_quotation_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_quotation_items_customer_quotation_id'), ['customer_quotation_id'], unique=False)

    op.create_table('quotation_request_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quotation_request_id', sa.Integer(), nullable=False),
    sa.Column('material_name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['quotation_request_id'], ['quotation_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quotation_request_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quotation_request_items_quotation_request_id'), ['quotation_request_id'], unique=False)

    op.create_table('supplier_quotation_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_quotation_id', sa.Integer(), nullable=False),
    sa.Column('material_name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['supplier_quotation_id'], ['supplier_quotations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('supplier_quotation_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supplier_quotation_items_supplier_quotation_id'), ['supplier_quotation_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplier_quotation_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supplier_quotation_items_supplier_quotation_id'))

    op.drop_table('supplier_quotation_items')
    with op.batch_alter_table('quotation_request_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quotation_request_items_quotation_request_id'))

    op.drop_table('quotation_request_items')
    with op.batch_alter_table('customer_quotation_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_quotation_items_customer_quotation_id'))

    op.drop_table('customer_quotation_items')
    with op.batch_alter_table('supplier_quotations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supplier_quotations_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_supplier_quotations_project_id'))

    op.drop_table('supplier_quotations')
    with op.batch_alter_table('quotation_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quotation_requests_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_quotation_requests_project_id'))

    op.drop_table('quotation_requests')
    with op.batch_alter_table('customer_quotations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_quotations_project_id'))
        batch_op.drop_index(batch_op.f('ix_customer_quotations_customer_id'))

    op.drop_table('customer_quotations')
    # ### end Alembic commands ###
