"""add description to project steps

Revision ID: dcd88654d914
Revises: ff6c39a87bd3
Create Date: 2026-08-27 17:15:35.946292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcd88654d914'
down_revision = 'ff6c39a87bd3'
branch_labels = None
depends_on = None


def upgrade():
    # 1. Add the column temporarily as nullable
    with op.batch_alter_table("project_steps", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "description",
                sa.Text(),
                nullable=True,
            )
        )

    # 2. Populate descriptions for existing rows
    descriptions = {
        1: "Customer shares the material or equipment requirement with S.T.",
        2: "S.T. forwards the requirement to the overseas partner or supplier for pricing.",
        3: "The supplier returns pricing, lead time, and terms for the requested material.",
        4: "Landed cost, duties, margin, and freight are worked into an internal cost sheet.",
        5: "A formal quotation is issued to the customer based on the cost sheet.",
        6: "The customer floats a tender based on the quoted scope.",
        7: "S.T. prepares and submits the technical and commercial bid.",
        8: "On winning the bid, the customer issues an official PO to S.T.",
        9: "S.T. confirms the order with the foreign partner or supplier.",
        10: "The supplier issues billing, triggering the advance payment terms.",
        11: "Goods arrive at the Indian port or airport for clearance.",
        12: "Import documentation, duties, and customs formalities are completed.",
        13: "Material reaches the customer's site along with S.T.'s invoice.",
        14: "Customer settles the invoice raised by S.T.",
        15: "S.T. clears the balance payment owed to the supplier.",
    }

    for step_number, description in descriptions.items():
        op.execute(
            sa.text(
                """
                UPDATE project_steps
                SET description = :description
                WHERE step_number = :step_number
                  AND description IS NULL
                """
            ).bindparams(
                description=description,
                step_number=step_number,
            )
        )

    # 3. Existing rows now have descriptions, so make it NOT NULL
    with op.batch_alter_table("project_steps", schema=None) as batch_op:
        batch_op.alter_column(
            "description",
            existing_type=sa.Text(),
            nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_steps', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
