"""add workflow models group 4

Revision ID: f6e2556b2a52
Revises: 17f9c47425ed
Create Date: 2026-08-25 18:27:43.573309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6e2556b2a52'
down_revision = '17f9c47425ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bills_of_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('bill_of_entry_number', sa.String(length=100), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('bcd', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('sws', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('igst', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_assessable_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bills_of_entry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bills_of_entry_project_id'), ['project_id'], unique=False)

    op.create_table('import_logistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('logistic_type', sa.String(length=50), nullable=False),
    sa.Column('airway_bill_number', sa.String(length=100), nullable=True),
    sa.Column('logistics_date', sa.Date(), nullable=False),
    sa.Column('flight_name', sa.String(length=255), nullable=True),
    sa.Column('flight_number', sa.String(length=100), nullable=True),
    sa.Column('airport_of_loading', sa.String(length=255), nullable=True),
    sa.Column('port_of_discharge', sa.String(length=255), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('import_logistics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_logistics_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_logistics_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('supplier_invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=100), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('delivery_terms', sa.String(length=100), nullable=True),
    sa.Column('payment_terms', sa.String(length=255), nullable=True),
    sa.Column('warranty_period', sa.String(length=100), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('supplier_invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supplier_invoices_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_invoices_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('supplier_packing_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('packing_list_number', sa.String(length=100), nullable=False),
    sa.Column('packing_list_date', sa.Date(), nullable=False),
    sa.Column('packing_condition', sa.String(length=255), nullable=True),
    sa.Column('total_gross_weight_kg', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('supplier_packing_lists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supplier_packing_lists_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_packing_lists_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('customs_clearances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('bill_of_entry_id', sa.Integer(), nullable=False),
    sa.Column('cha_name', sa.String(length=255), nullable=False),
    sa.Column('customs_location_port', sa.String(length=255), nullable=False),
    sa.Column('duty_paid_date', sa.Date(), nullable=True),
    sa.Column('challan_number', sa.String(length=100), nullable=True),
    sa.Column('cfs_name', sa.String(length=255), nullable=True),
    sa.Column('transaction_payment_reference', sa.String(length=255), nullable=True),
    sa.Column('duty_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('igst_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('other_customs_charges', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bill_of_entry_id'], ['bills_of_entry.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customs_clearances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customs_clearances_bill_of_entry_id'), ['bill_of_entry_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customs_clearances_project_id'), ['project_id'], unique=False)

    op.create_table('supplier_invoice_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_invoice_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('hsn_sac', sa.String(length=50), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['supplier_invoice_id'], ['supplier_invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('supplier_invoice_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supplier_invoice_items_supplier_invoice_id'), ['supplier_invoice_id'], unique=False)

    op.create_table('supplier_packing_list_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('packing_list_id', sa.Integer(), nullable=False),
    sa.Column('material_description', sa.String(length=500), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('unit_weight_kg', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['packing_list_id'], ['supplier_packing_lists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('supplier_packing_list_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supplier_packing_list_items_packing_list_id'), ['packing_list_id'], unique=False)

    op.create_table('supplier_proforma_invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('order_confirmation_id', sa.Integer(), nullable=True),
    sa.Column('proforma_invoice_number', sa.String(length=100), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('delivery_terms', sa.String(length=100), nullable=True),
    sa.Column('delivery_date', sa.Date(), nullable=True),
    sa.Column('payment_terms', sa.String(length=255), nullable=True),
    sa.Column('warranty_period', sa.String(length=100), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_confirmation_id'], ['supplier_order_confirmations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('supplier_proforma_invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supplier_proforma_invoices_order_confirmation_id'), ['order_confirmation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_proforma_invoices_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_proforma_invoices_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('supplier_proforma_invoice_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proforma_invoice_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('hsn_sac', sa.String(length=50), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['proforma_invoice_id'], ['supplier_proforma_invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('supplier_proforma_invoice_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supplier_proforma_invoice_items_proforma_invoice_id'), ['proforma_invoice_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplier_proforma_invoice_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supplier_proforma_invoice_items_proforma_invoice_id'))

    op.drop_table('supplier_proforma_invoice_items')
    with op.batch_alter_table('supplier_proforma_invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supplier_proforma_invoices_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_supplier_proforma_invoices_project_id'))
        batch_op.drop_index(batch_op.f('ix_supplier_proforma_invoices_order_confirmation_id'))

    op.drop_table('supplier_proforma_invoices')
    with op.batch_alter_table('supplier_packing_list_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supplier_packing_list_items_packing_list_id'))

    op.drop_table('supplier_packing_list_items')
    with op.batch_alter_table('supplier_invoice_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supplier_invoice_items_supplier_invoice_id'))

    op.drop_table('supplier_invoice_items')
    with op.batch_alter_table('customs_clearances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customs_clearances_project_id'))
        batch_op.drop_index(batch_op.f('ix_customs_clearances_bill_of_entry_id'))

    op.drop_table('customs_clearances')
    with op.batch_alter_table('supplier_packing_lists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supplier_packing_lists_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_supplier_packing_lists_project_id'))

    op.drop_table('supplier_packing_lists')
    with op.batch_alter_table('supplier_invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supplier_invoices_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_supplier_invoices_project_id'))

    op.drop_table('supplier_invoices')
    with op.batch_alter_table('import_logistics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_logistics_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_import_logistics_project_id'))

    op.drop_table('import_logistics')
    with op.batch_alter_table('bills_of_entry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bills_of_entry_project_id'))

    op.drop_table('bills_of_entry')
    # ### end Alembic commands ###
